### PR TITLE
getTransactionsMany parsing and a few other changes

### PR DESCRIPTION
**Pull request by piggydoughnut**
- Changes in README
  - started adding basic API description
  - added a sample for output for getTransactionsMany
- replaced direct reference to wasm with an npm library (@tokel/cryptoconditions)
- exposing nspvConnect function to be used for connecting to nspv instead of manually creating a peer group.

### CODE REVIEW

**Comment by dimxy** [comment]
I ran 'npm update' and it stalled on read-shrinkwrap
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
The authenticity of host 'github.com (140.82.121.4)' can't be established.ed to /Users/dimxy/repo/bitgo-komodo-cc-lib/node
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? ⸨           ░░░░░░░⸩
```

Seems it did not stall but was asking for yes/no but when I entered 'yes' it failed with 
```
Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/BitGo/blake2b.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
```

**Comment by dimxy** [comment]
Some more notes:
- I'd like to have the to cryptoconditons-js lib link to my repo to be able to fix it
- there is no cctokensv2tokel.js any more, all tokens code is now in cctokensv2.js
- we do not need general.js/keyToWif, I believe the ECPair lib already has toWIF function

**Comment by dimxy** [comment]
The update to readme states:
```
Open `config` folder and rename `index.sample.js` to `index.js` and chage `yourchainname` and `magic` params for your chain.
```
I'd like the configuration for all chains to be stored in the networks.js source file (like the libnspv has its 'coins' config file). So no need to rename any files, if there is no a config for some chain it should be added to networks.js and 'var mynetwork' initialised with this chain

**Comment by piggydoughnut** [comment]
> The update to readme states:
> 
> ```
> Open `config` folder and rename `index.sample.js` to `index.js` and chage `yourchainname` and `magic` params for your chain.
> ```
> 
> I'd like the configuration for all chains to be stored in the networks.js source file (like the libnspv has its 'coins' config file). So no need to rename any files, if there is no a config for some chain it should be added to networks.js and 'var mynetwork' initialised with this chain

oh yeah I ll remove that, its all in networks. I am not using that config anymore.

**Comment by piggydoughnut** [comment]
> Some more notes:
> 
>     * I'd like to have the to cryptoconditons-js lib link to my repo to be able to fix it

I think we have some options here:
- It can be a local development option. Aka when you develop you can swap that library for your repo. But the final library should have a reference to an npm package, which I will update every time you push changes.
- You publish your npm cryptoconditions package and develop the package locally. We will use your npm package.
- You can cherry-pick the transaction parsing function from my code and leave the rest as is.

If you want this tech to be used by wider audience though you cannot expect them to manually compile things inside the node_modules. It should be easy to install.


>     * there is no cctokensv2tokel.js any more, all tokens code is now in cctokensv2.js

ok, will remove that. Must have sneaked during merge. Thx for noticing

>     * we do not need general.js/keyToWif, I believe the ECPair lib already has toWIF function

Well I would to provide an easy to use interface to users, and simply using keyToWif instead of learning how to use ECPair sounds like a good alternative to me.

**Comment by dimxy** [comment]
> I ran 'npm update' and it stalled on read-shrinkwrap
> 
> ```
> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
> The authenticity of host 'github.com (140.82.121.4)' can't be established.ed to /Users/dimxy/repo/bitgo-komodo-cc-lib/node
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no/[fingerprint])? ⸨           ░░░░░░░⸩
> ```
> 
> Seems it did not stall but was asking for yes/no but when I entered 'yes' it failed with
> 
> ```
> Error while executing:
> npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/BitGo/blake2b.git
> npm ERR! 
> npm ERR! git@github.com: Permission denied (publickey).
> npm ERR! fatal: Could not read from remote repository.
> ```

I should not run npm update for all packages.
Removing the previous package-lock and rerunning 'npm install' fixed the issue

**Comment by dimxy** [comment]
Regarding the cc lib let's leave it as you made it for now, I'll be switching to my repo if needed

> Well I would to provide an easy to use interface to users, and simply using keyToWif instead of learning how to use ECPair sounds like a good alternative to me.
okay, I may have missed the point what keyToWif does

**Pull request merged**
